name: Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: enter aws lightsail via SSH & Deploy
        run: |
          cd ~/.ssh
          ssh -i id_rsa ${{ secrets.USER }}@${{ secrets.IP }} "
            cd /srv/projects/YIT_Coursework/
            git pull origin main
            rm -rf .parcel-cache/ dist/
            parcel build src/*.html --public-url /
          "
