name: Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Debugging line to check the content of known_hosts

      - name: Enter AWS Lightsail via SSH & Deploy
        run: |
          cd ~/.ssh
          ssh -i id_rsa ubuntu@13.38.72.193 "
            whoami
            node -v
            npm -v
            cd /srv/projects/YIT_Coursework/
            git pull origin main
            rm -rf node_modules
            rm -rf .parcel-cache
            rm -rf dist/
            npm install
            npm run build -- --public-url /
          "