name: Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH & Deploy
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.IP }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: ${{ secrets.SSH_PUBLIC_KEY }}
          connect_timeout: 10s
          script: |
            cd /srv/projects/YIT_Coursework/
            git pull origin main
            rm -rf .parcel-cache/ dist/
            parcel build src/*.html --public-url /
