name: Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Debugging line to check the content of known_hosts

      - name: Enter AWS Lightsail via SSH & Deploy
        run: |
          cd ~/.ssh
          ssh -i id_rsa ubuntu@13.38.72.193 "
            whoami
            export PATH="/home/ubuntu/.local/bin:/home/ubuntu/.nvm/versions/node/v21.3.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$PATH"
            nvm use 21
            node -v
            npm -v
            cd /srv/projects/YIT_Coursework/
            git pull origin main
            rm -rf node_modules
            rm -rf .parcel-cache
            rm -rf dist/
            npm install
            parcel build src/*.html --public-url /
          "